import type { CardDefinition } from '../../shared/types';

export const CARDS: CardDefinition[] = [
  // ── Mycorrhizal (14) ────────────────────────────────────────────────────────
  {
    id: 1,
    name: 'Chanterelle',
    scientificName: 'Cantharellus cibarius',
    cost: 2,
    pts: 6,
    generates: { spore: 1 },
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] +1 bonus point per 3 tiles in your network (rounded down).',
  },
  {
    id: 8,
    name: 'Chaga',
    scientificName: 'Inonotus obliquus',
    cost: 3,
    pts: 3,
    generates: {},
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: true,
    power: '[Ongoing] +1 point every 3 turns it survives on the board.',
  },
  {
    id: 10,
    name: 'Saffron Milky Cap',
    scientificName: 'Lactarius deliciosus',
    cost: 2,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] Immediately gain 2 spores.',
  },
  {
    id: 11,
    name: 'Morel',
    scientificName: 'Morchella esculenta',
    cost: 4,
    pts: 7,
    generates: { spore: 1 },
    habitats: ['decay', 'tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] +1 bonus point if spawned on an Open tile.',
  },
  {
    id: 12,
    name: 'King Bolete',
    scientificName: 'Boletus edulis',
    cost: 4,
    pts: 8,
    generates: { moisture: 1 },
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] All adjacent friendly mushrooms each score +1 point.',
  },
  {
    id: 13,
    name: 'Black Truffle',
    scientificName: 'Tuber melanosporum',
    cost: 5,
    pts: 8,
    generates: {},
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[Passive] No special ability — pure prestige points.',
  },
  {
    id: 14,
    name: 'Matsutake',
    scientificName: 'Tricholoma murrillianum',
    cost: 4,
    pts: 3,
    generates: { sunlight: 1 },
    habitats: ['tree', 'shade'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] +3 bonus points if you own no other mushroom of the same type.',
  },
  {
    id: 15,
    name: 'Golden Chanterelle',
    scientificName: 'Cantharellus formosus',
    cost: 3,
    pts: 2,
    generates: { spore: 1 },
    habitats: ['tree', 'shade'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] +2 points per other Chanterelle variant you own.',
  },
  {
    id: 17,
    name: 'Hedgehog',
    scientificName: 'Hydnum repandum',
    cost: 3,
    pts: 4,
    generates: { moisture: 1 },
    habitats: ['tree', 'shade'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] +3 bonus points if no opponent has mushrooms on adjacent tiles.',
  },
  {
    id: 20,
    name: 'Coral Mushroom',
    scientificName: 'Ramaria botrytis',
    cost: 3,
    pts: 2,
    generates: { sunlight: 1 },
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] +1 point per 5 tiles in your network (rounded down).',
  },
  {
    id: 38,
    name: 'Indigo Milky Cap',
    scientificName: 'Lactarius indigo',
    cost: 3,
    pts: 3,
    generates: { moisture: 1 },
    habitats: ['tree', 'shade'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[When Spawned] Permanently reduce the spread cost of all adjacent tiles to 1.',
  },
  {
    id: 41,
    name: 'Amanita Caesar',
    scientificName: 'Amanita caesarea',
    cost: 5,
    pts: 10,
    generates: { spore: 1 },
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[Passive] No special ability — pure prestige points.',
  },
  {
    id: 43,
    name: 'Old Man of the Woods',
    scientificName: 'Strobilomyces strobilaceus',
    cost: 3,
    pts: 2,
    generates: { sunlight: 1 },
    habitats: ['tree', 'shade'],
    type: 'mycorrhizal',
    isOngoing: true,
    power: '[Ongoing] +1 point each turn it remains on the board.',
  },
  {
    id: 45,
    name: 'Hen Egg Bolete',
    scientificName: 'Boletus projectellus',
    cost: 3,
    pts: 5,
    generates: { moisture: 1 },
    habitats: ['tree'],
    type: 'mycorrhizal',
    isOngoing: false,
    power: '[Passive] Cannot be affected by any adjacency disruption or seasonal effects.',
  },

  // ── Saprophytic (14) ────────────────────────────────────────────────────────
  {
    id: 2,
    name: 'Oyster Mushroom',
    scientificName: 'Pleurotus ostreatus',
    cost: 2,
    pts: 3,
    generates: { spore: 1 },
    habitats: ['wet'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[When Spawned] Place up to 2 free copies on adjacent network tiles.',
  },
  {
    id: 3,
    name: 'Shiitake',
    scientificName: 'Lentinula edodes',
    cost: 3,
    pts: 5,
    generates: { moisture: 1 },
    habitats: ['decay', 'tree', 'shade'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[Player Choice] Sacrifice 1 moisture to gain 1 sunlight.',
  },
  {
    id: 5,
    name: 'Turkey Tail',
    scientificName: 'Trametes versicolor',
    cost: 2,
    pts: 3,
    generates: { sunlight: 1 },
    habitats: ['decay', 'shade'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[Passive] Cannot be affected by negative season effects. Always generates resources.',
  },
  {
    id: 9,
    name: "Lion's Mane",
    scientificName: 'Hericium erinaceus',
    cost: 3,
    pts: 3,
    generates: { sunlight: 2 },
    habitats: ['decay', 'tree'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[On Draw] Once per turn, your first Draw action draws 1 extra card for free.',
  },
  {
    id: 19,
    name: 'Wood Ear',
    scientificName: 'Auricularia auricula-judae',
    cost: 2,
    pts: 4,
    generates: { moisture: 2 },
    habitats: ['wet'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[Passive] Not affected by negative season effects.',
  },
  {
    id: 31,
    name: 'Puffball',
    scientificName: 'Calvatia gigantea',
    cost: 1,
    pts: 0,
    generates: {},
    habitats: ['tree', 'wet'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[When Spawned] Your network expands to 1 random adjacent unoccupied tile.',
  },
  {
    id: 32,
    name: 'Inky Cap',
    scientificName: 'Coprinopsis atramentaria',
    cost: 1,
    pts: 0,
    generates: { moisture: 1 },
    habitats: ['wet', 'decay'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[Player Choice] Discard during Collect phase to gain 3 spores.',
  },
  {
    id: 33,
    name: "Dryad's Saddle",
    scientificName: 'Cerioporus squamosus',
    cost: 2,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['tree', 'decay'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[Ongoing] During Spring, generates +1 additional spore.',
  },
  {
    id: 34,
    name: 'Chicken of the Woods',
    scientificName: 'Laetiporus sulphureus',
    cost: 3,
    pts: 1,
    generates: { spore: 2 },
    habitats: ['tree', 'decay'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[When Spawned] Immediately gain 2 moisture.',
  },
  {
    id: 37,
    name: 'Shaggy Mane',
    scientificName: 'Coprinus comatus',
    cost: 2,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['wet'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[When Spawned] +3 pts each for this and one adjacent friendly mushroom.',
  },
  {
    id: 40,
    name: 'Velvet Foot',
    scientificName: 'Flammulina populicola',
    cost: 2,
    pts: 1,
    generates: { moisture: 1 },
    habitats: ['decay', 'wet'],
    type: 'saprophytic',
    isOngoing: true,
    power: '[Ongoing] +1 moisture in Winter. Immune to winter seasonal effects.',
  },
  {
    id: 44,
    name: "Bear's Head Tooth",
    scientificName: 'Hericium americanum',
    cost: 4,
    pts: 4,
    generates: { sunlight: 2 },
    habitats: ['decay', 'tree'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[On Draw] The first card drawn each turn costs 0 sunlight.',
  },
  {
    id: 47,
    name: 'Angel Wings',
    scientificName: 'Pleurocybella porrigens',
    cost: 2,
    pts: 1,
    generates: { sunlight: 1 },
    habitats: ['decay', 'shade'],
    type: 'saprophytic',
    isOngoing: true,
    power: '[Ongoing] +3 pts/turn in Summer. No resources or points in Winter.',
  },
  {
    id: 48,
    name: 'Gem-Studded Puffball',
    scientificName: 'Lycoperdon perlatum',
    cost: 1,
    pts: 2,
    generates: {},
    habitats: ['tree', 'decay'],
    type: 'saprophytic',
    isOngoing: false,
    power: '[When Spawned] Gain 2 spores immediately.',
  },

  // ── Symbiotic (7) ───────────────────────────────────────────────────────────
  {
    id: 4,
    name: 'Maitake',
    scientificName: 'Grifola frondosa',
    cost: 3,
    pts: 3,
    generates: { sunlight: 1 },
    habitats: ['tree', 'decay'],
    type: 'symbiotic',
    isOngoing: true,
    power: '[End of Turn] If on a Tree tile, draw 1 free card at end of your turn.',
  },
  {
    id: 6,
    name: 'Reishi',
    scientificName: 'Ganoderma lucidum',
    cost: 4,
    pts: 7,
    generates: { moisture: 2 },
    habitats: ['shade'],
    type: 'symbiotic',
    isOngoing: true,
    power: '[Passive] Immune to all negative season effects.',
  },
  {
    id: 7,
    name: 'Honey Mushroom',
    scientificName: 'Armillaria mellea',
    cost: 2,
    pts: 0,
    generates: { moisture: 2 },
    habitats: ['tree', 'decay'],
    type: 'symbiotic',
    isOngoing: true,
    power: '[Ongoing] Reduces spread cost for adjacent network tiles by 1 (minimum 1).',
  },
  {
    id: 16,
    name: 'Lobster Mushroom',
    scientificName: 'Hypomyces lactifluorum',
    cost: 3,
    pts: 2,
    generates: { spore: 1 },
    habitats: ['shade', 'tree'],
    type: 'symbiotic',
    isOngoing: true,
    power: '[Ongoing] Each Collect: one adjacent friendly scores +1 point.',
  },
  {
    id: 35,
    name: 'Enoki',
    scientificName: 'Flammulina velutipes',
    cost: 2,
    pts: 3,
    generates: { moisture: 1 },
    habitats: ['wet'],
    type: 'symbiotic',
    isOngoing: true,
    power: '[Ongoing] During Winter, scores +2 points per adjacent friendly mushroom.',
  },
  {
    id: 39,
    name: 'Candy Cap',
    scientificName: 'Lactarius rubidus',
    cost: 4,
    pts: 4,
    generates: { sunlight: 1 },
    habitats: ['shade'],
    type: 'symbiotic',
    isOngoing: true,
    power: '[Ongoing] Each adjacent friendly sunlight generator produces +2 extra.',
  },
  {
    id: 49,
    name: 'Scarlet Waxy Cap',
    scientificName: 'Hygrocybe coccinea',
    cost: 2,
    pts: 3,
    generates: { moisture: 1 },
    habitats: ['wet'],
    type: 'symbiotic',
    isOngoing: false,
    power: '[Start of Season] At Autumn start, place 2 free copies on adjacent tiles.',
  },

  // ── Parasitic (8) ───────────────────────────────────────────────────────────
  {
    id: 21,
    name: 'Fly Agaric',
    scientificName: 'Amanita muscaria',
    cost: 3,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['tree', 'shade'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Adjacent opponents generate 1 fewer resource/turn.',
  },
  {
    id: 22,
    name: 'Destroying Angel',
    scientificName: 'Amanita bisporigera',
    cost: 4,
    pts: 2,
    generates: { sunlight: 1 },
    habitats: ['tree'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Opponents must pay +2 spores to spawn on tiles adjacent to this mushroom.',
  },
  {
    id: 23,
    name: 'Death Cap',
    scientificName: 'Amanita phalloides',
    cost: 4,
    pts: 7,
    generates: { spore: 2 },
    habitats: ['shade'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Adjacent opponents generate no resources (still score).',
  },
  {
    id: 25,
    name: 'False Morel',
    scientificName: 'Gyromitra esculenta',
    cost: 2,
    pts: 2,
    generates: { spore: 1 },
    habitats: ['tree'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Any type for Mycelium Harmony. Redeclare each Collect in Winter.',
  },
  {
    id: 26,
    name: 'Panther Cap',
    scientificName: 'Amanita pantherina',
    cost: 3,
    pts: 5,
    generates: { moisture: 1 },
    habitats: ['tree', 'shade'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Opponents pay +1 moisture to spread into adjacent tiles.',
  },
  {
    id: 27,
    name: 'Stinkhorn',
    scientificName: 'Phallus impudicus',
    cost: 1,
    pts: 0,
    generates: {},
    habitats: ['decay'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Opponents can\'t spawn on adjacent tiles.',
  },
  {
    id: 28,
    name: 'Deadly Galerina',
    scientificName: 'Galerina marginata',
    cost: 2,
    pts: 1,
    generates: { sunlight: 1 },
    habitats: ['decay', 'shade'],
    type: 'parasitic',
    isOngoing: true,
    power: '[Ongoing] Adjacent opponents generate 1 fewer resource/turn.',
  },
  {
    id: 30,
    name: 'Pigskin Puffball',
    scientificName: 'Scleroderma citrinum',
    cost: 1,
    pts: 0,
    generates: {},
    habitats: ['tree'],
    type: 'parasitic',
    isOngoing: false,
    power: '[When Spawned] Blocks opponent spreading into adjacent tiles this season.',
  },

  // ── Opportunistic (7) ───────────────────────────────────────────────────────
  {
    id: 18,
    name: 'Cauliflower Mushroom',
    scientificName: 'Sparassis crispa',
    cost: 4,
    pts: 5,
    generates: { spore: 1 },
    habitats: ['tree'],
    type: 'opportunistic',
    isOngoing: false,
    power: '[When Spawned] Immediately score 2 bonus points.',
  },
  {
    id: 24,
    name: "Jack O'Lantern",
    scientificName: 'Omphalotus olearius',
    cost: 2,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['decay', 'tree'],
    type: 'opportunistic',
    isOngoing: true,
    power: '[Ongoing] Opponents must pay +1 spore to spawn on tiles adjacent to this mushroom.',
  },
  {
    id: 29,
    name: "Witch's Butter",
    scientificName: 'Tremella mesenterica',
    cost: 1,
    pts: 0,
    generates: { sunlight: 1 },
    habitats: ['decay', 'wet'],
    type: 'opportunistic',
    isOngoing: true,
    power: '[Ongoing] Opponents must pay +1 moisture to spread into tiles adjacent to this mushroom.',
  },
  {
    id: 36,
    name: 'Black Trumpet',
    scientificName: 'Craterellus cornucopioides',
    cost: 3,
    pts: 4,
    generates: { sunlight: 1 },
    habitats: ['shade', 'wet'],
    type: 'opportunistic',
    isOngoing: false,
    power: '[Passive] Cannot be targeted by opponent adjacency disruption abilities.',
  },
  {
    id: 42,
    name: "Hen's Egg Stinkhorn",
    scientificName: 'Phallus hadriani',
    cost: 2,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['decay'],
    type: 'opportunistic',
    isOngoing: false,
    power: '[When Spawned] On the following turn, choose 2 adjacent tiles to spread to for free.',
  },
  {
    id: 46,
    name: 'Cinnabar Chanterelle',
    scientificName: 'Cantharellus cinnabarinus',
    cost: 2,
    pts: 1,
    generates: { spore: 1 },
    habitats: ['tree', 'shade'],
    type: 'opportunistic',
    isOngoing: true,
    power: '[Ongoing] Scores +2 bonus points per turn during Summer and Long Summer.',
  },
  {
    id: 50,
    name: 'Blewit',
    scientificName: 'Clitocybe nuda',
    cost: 3,
    pts: 5,
    generates: { spore: 1 },
    habitats: ['decay', 'shade'],
    type: 'opportunistic',
    isOngoing: true,
    power: '[Ongoing] Autumn: +1 spore and +1 point per turn.',
  },
];

export const CARD_MAP = new Map<number, CardDefinition>(
  CARDS.map(c => [c.id, c])
);

export function getCard(id: number): CardDefinition {
  const card = CARD_MAP.get(id);
  if (!card) throw new Error(`Unknown card id: ${id}`);
  return card;
}
